# Change these first
owner: getjerry # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Homepage
    url: https://jerry.ai
  - name: Insurance System
    url: https://jerry.ai/health
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jerry.ai
  # baseUrl: /your-repo-name
  logoUrl: https://jerry.ai/imgs/icon-app.png
  name: Jerry Status
  introTitle: "**Jerry Status** - Real-time Uptime Monitoring"
  introMessage: This is Jerry's status page which uses **real-time** data from our [GitHub repository](https://github.com/getjerry/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
